Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd     = os.path.join(str(Dir('#')), 'applications')

# add the general drvers.
src = Split("""
application.c
startup.c
menu.c
keyprocess_t.c
menu_1.c
menu_2.c
menu_3.c
accountop.c
gui.c
unlock_ui.c
KeyModifyUI.c
buzzer.c
gprs.c
gprsmailclass.c
FprintHandle.c
dataSYNS.c
eeprom_process.c
debug_manage.c
PowerManage.c
UserManageUI.c
""")

CPPPATH = [cwd, str(Dir('#'))]
group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
