Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = os.path.join(str(Dir('#')), 'net')

# add the general drvers.
src = Split("""
crc16.c
crc32.c
des.c
netcomm.c
netfile.c
netmailclass.c
netphysics.c
netprotocol.c
netkey.c
netphone.c
netaccount.c
netbind.c
netterminal.c
""")

CPPPATH = [cwd, str(Dir('#'))]
group = DefineGroup('Net', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
